/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Visit } from "./Visit";
import { VisitCountArgs } from "./VisitCountArgs";
import { VisitFindManyArgs } from "./VisitFindManyArgs";
import { VisitFindUniqueArgs } from "./VisitFindUniqueArgs";
import { CreateVisitArgs } from "./CreateVisitArgs";
import { UpdateVisitArgs } from "./UpdateVisitArgs";
import { DeleteVisitArgs } from "./DeleteVisitArgs";
import { SampleFindManyArgs } from "../../sample/base/SampleFindManyArgs";
import { Sample } from "../../sample/base/Sample";
import { Store } from "../../store/base/Store";
import { User } from "../../user/base/User";
import { VisitService } from "../visit.service";
@graphql.Resolver(() => Visit)
export class VisitResolverBase {
  constructor(protected readonly service: VisitService) {}

  async _visitsMeta(
    @graphql.Args() args: VisitCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Visit])
  async visits(@graphql.Args() args: VisitFindManyArgs): Promise<Visit[]> {
    return this.service.visits(args);
  }

  @graphql.Query(() => Visit, { nullable: true })
  async visit(
    @graphql.Args() args: VisitFindUniqueArgs
  ): Promise<Visit | null> {
    const result = await this.service.visit(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Visit)
  async createVisit(@graphql.Args() args: CreateVisitArgs): Promise<Visit> {
    return await this.service.createVisit({
      ...args,
      data: {
        ...args.data,

        store: args.data.store
          ? {
              connect: args.data.store,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Visit)
  async updateVisit(
    @graphql.Args() args: UpdateVisitArgs
  ): Promise<Visit | null> {
    try {
      return await this.service.updateVisit({
        ...args,
        data: {
          ...args.data,

          store: args.data.store
            ? {
                connect: args.data.store,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Visit)
  async deleteVisit(
    @graphql.Args() args: DeleteVisitArgs
  ): Promise<Visit | null> {
    try {
      return await this.service.deleteVisit(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Sample], { name: "samples" })
  async findSamples(
    @graphql.Parent() parent: Visit,
    @graphql.Args() args: SampleFindManyArgs
  ): Promise<Sample[]> {
    const results = await this.service.findSamples(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Store, {
    nullable: true,
    name: "store",
  })
  async getStore(@graphql.Parent() parent: Visit): Promise<Store | null> {
    const result = await this.service.getStore(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Visit): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
